version: '3.1'

services:
  wordpress:
    image: wordpress:5.6-php7.4
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_HTTP_BLOCK_EXTERNAL', ! defined( 'WP_CLI' ) );
    volumes:
      - wordpress_data:/var/www/html
      - ../../:/var/www/html/wp-content/plugins/google-site-kit
      - ../../tests/e2e/plugins:/var/www/html/wp-content/plugins/google-site-kit-test-plugins
      - ../../tests/e2e/mu-plugins:/var/www/html/wp-content/mu-plugins
    depends_on:
      - mysql
      - http_proxy
    networks:
      - internal_network

  http_proxy:
    image: nginx
    restart: always
    ports:
      - 9002:80
    volumes:
      - ./config/nginx-http-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - internal_network

  cli:
    image: wordpress:cli
    restart: always
    user: xfs
    volumes:
      - wordpress_data:/var/www/html
      - ../../:/var/www/html/wp-content/plugins/google-site-kit
      - ../../tests/e2e/mu-plugins:/var/www/html/wp-content/mu-plugins
    depends_on:
      - mysql
      - wordpress
    command: tail -f /dev/null
    networks:
      - default

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test
    networks:
      - default
      - internal_network

volumes:
  wordpress_data:

networks:
  internal_network:
    internal: true # No external connections allowed
