name: Checklists

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - reopened
      - edited

jobs:
  checklist:
    name: Checklist Checks
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Check non-resolved tasks
        if: contains(github.event.pull_request.body, '- [ ]')
        run: exit 1
