name: Compressed Size

on:
  pull_request:
    branches:
      - develop
      - master
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'assets/js/**.js'
      - '!assets/js/**.test.js'
      - '!assets/js/**/test/**'
      - 'assets/sass/**/*.scss'
      - 'assets/svg/**/*.svg'
      - './*.config.js'
      - './package-lock.json'

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "./dist/assets/**/*.{css,js}"
          # The sub-match below will be replaced by asterisks.
          # The length of 20 corresponds to webpack's `output.hashDigestLength`.
          strip-hash: "\\.([a-f0-9]{20})\\.(?:css|js)$"
