name: E2E Tests

on:
  push:
    branches:
      - develop
      - main
    # Ignore Storybook-only and unit-test-only changes when checking to run
    # E2E tests. This is useful when adding/modifying/refactoring/removing
    # test code ONLY in a commit, but saves running the expensive E2E test
    # suite on GitHub Actions when all that's changing are tests and not code
    # that would affect E2E behavior.
    paths:
      - '.github/workflows/e2e-tests-wp-nightly.yml'
      - '.babelrc'
      - 'assets/**'
      - 'includes/**'
      - '/*.php'
      - 'jest-puppeteer.config.js'
      - 'composer.json'
      - 'composer.lock'
      - '/php-scoper/composer.lock'
      - 'package.json'
      - 'package-lock.json'
      - 'postcss.config.js'
      - 'webpack.config.js'
      - 'tests/e2e/**'
      - '!assets/**/__tests__/**/*.js'
      - '!assets/**/test/*.js'
      - '!assets/**/*.test.js'
      - '!packages/**/__tests__/**/*.js'
      - '!packages/**/test/*.js'
      - '!packages/**/*.test.js'
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'
    # Ignore Storybook-only and unit-test-only changes when checking to run
    # E2E tests. This is useful when adding/modifying/refactoring/removing
    # test code ONLY in a commit, but saves running the expensive E2E test
    # suite on GitHub Actions when all that's changing are tests and not code
    # that would affect E2E behavior.
    paths:
      - '.github/workflows/e2e-tests-wp-nightly.yml'
      - '.babelrc'
      - 'assets/**'
      - 'includes/**'
      - '/*.php'
      - 'jest-puppeteer.config.js'
      - 'composer.json'
      - 'composer.lock'
      - '/php-scoper/composer.lock'
      - 'package.json'
      - 'package-lock.json'
      - 'postcss.config.js'
      - 'webpack.config.js'
      - 'tests/e2e/**'
      - '!assets/**/__tests__/**/*.js'
      - '!assets/**/test/*.js'
      - '!assets/**/*.test.js'
      - '!packages/**/__tests__/**/*.js'
      - '!packages/**/test/*.js'
      - '!packages/**/*.test.js'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: e2e-tests-wp-nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests-wp-nightly:
    name: E2E (WordPress nightly)

    env:
      WP_VERSION: nightly

    runs-on: ubuntu-latest

    timeout-minutes: 30

    if: github.event_name == 'push' || github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v2

      - name: Composer Install
        uses: ./.github/actions/composer

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: npm install
        run: npm ci

      - name: Build
        run: npm run build:test

      - name: Start environment
        run: npm run env:start

      - name: Run the tests
        run: npm run test:e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: e2e-screenshots
          path: tests/e2e/screenshots
