name: PHP Tests

on:
  push:
    branches:
      - develop
      - main
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-tests-wp-latest-multisite-php-7-4.yml'
      - includes/**
      - tests/phpunit/**
      - /*.php
      - 'phpunit*.xml*'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-tests-wp-latest-multisite-php-7-4.yml'
      - includes/**
      - tests/phpunit/**
      - /*.php
      - 'phpunit*.xml*'
      - 'composer.json'
      - 'composer.lock'
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: php-tests-wp-latest-multisite-php-7-4-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-tests-wp-latest-multisite-php-7-4:
    name: PHP (PHP 7.4, WordPress Latest, Multisite)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress_test
      WP_VERSION: latest
      WP_MULTISITE: "1"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          extensions: mysqli, runkit7, uopz
          php-version: "7.4"
      - name: Composer Install
        uses: ./.github/actions/composer
        with:
          dev: yes
      - name: Set up PHP test data
        run: tests/bin/install-wp-tests.sh ${MYSQL_DATABASE} ${MYSQL_USER} ${MYSQL_PASSWORD} ${DB_HOST}:${DB_PORT} ${WP_VERSION}
      - name: Run Unit Tests
        run: composer test:multisite -- --verbose
