name: Typo CI

on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  spellcheck:
    name: Typo CI (GitHub Action)
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
    - name: TypoCheck
      uses: typoci/spellcheck-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}