name: Visual Regression Testing

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
    # Only run if CSS/JS/MD-related files changed.
    paths:
      - '.github/workflows/visual-regression.yml'
      - 'assets/**'
      - '!assets/**/__tests__/**/*.js'
      - '!assets/**/test/*.js'
      - '!assets/**/*.test.js'
      - '**.stories.js'
      - 'tests/backstop/**'
      - '.storybook/**'
      - '**.scss'
      - '.nvmrc'
      - '**/package.json'
      - 'package-lock.json'
      - 'src/tests/backstop/config.js'
      - 'docker/backstopjs/Dockerfile'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: visual-regression-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-files:
    name: Build Files
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: npm install
        run: npm ci
      - name: Build Files
        run: VRT=1 npm run build:storybook
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: |
            dist
  visual-regression:
    name: Run VR Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build-files
    strategy:
      fail-fast: false
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-files
      - name: npm install
        run: npm ci
      - name: Run Backstopjs
        run: npm run backstopjs -- test ${{ matrix.shard }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vrt-report-${{ matrix.shard }}
          path: |
            tests/backstop/html_report
            tests/backstop/reference
            tests/backstop/tests
