name: Workflow Validation Testing

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
    paths:
      - '.github/**.yml'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: workflow-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  visual-regression:
    name: Run Workflow Validation
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
